name: CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        schema: [SampleSwift, SampleObjC]
        
    steps:
    - uses: actions/checkout@v2

    - name: Compile project
      run: |
        cd sample && xcodebuild build -scheme ${{ matrix.schema }} -destination 'name=iPhone 11'
